### ISSUE TITLE
Unable to publish to App Store - RevenueCat contains bitcode

### ISSUE THREAD

**Issue by varyamereon** [thisisthekap/Tonestro.Maui.RevenueCat.iOS#4]
When trying to publish an app to the App Store, I receive the following issue:

```
ITMS-90482: Invalid Executable - The executable 'Logbook.Maui.app/Frameworks/RevenueCat.framework/RevenueCat' contains bitcode.
```

I was looking at [this](https://github.com/dotnet/maui/issues/10989) as a potential workaround but maybe it's something you can look into?

**Comment by amit-isolufy** [comment]
@varyamereon The solutions you have mentioned that is not working. 

I'm using Sonoma 14.2 with Xcode 15 and .NET 7.0.

Based on the instruction I have tried to add build script. While generating build I'm getting following path.

**Build Logs**
**Target _CopyDirectoriesToBundle:**
    /usr/bin/ditto /obj/Release/net7.0-ios/ios-arm64/linker-cache/RevenueCat.framework/ /bin/Release/net7.0-ios/ios-arm64/<APP-NAME>.app/Frameworks/RevenueCat.framework --arch arm64
    
For other framework getting following output.

**Target _StripBitcodeFromFrameworksOnMac:**
    xcrun -find bitcode_strip
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip /.nuget/packages/skiasharp.nativeassets.ios/2.88.6/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp -r -o .nuget/packages/skiasharp.nativeassets.ios/2.88.6/runtimes/ios/native/libSkiaSharp.framework/libSkiaSharp
    
Did you able to fix issue ?
    
@albilaga @thisisthekap do you guys have any suggestions ?

**Comment by varyamereon** [comment]
Hi @amit-isolufy, yes.... I ended up using [this](https://github.com/Kebechet/Maui.RevenueCat.iOS) library instead, which was created to work around the bitcode issue. Tbh I am very grateful to the creator of this library for their work in the past, but it seems to no longer be being updated. I moved completely across to [this](https://github.com/Kebechet/Maui.RevenueCat.InAppBilling) which uses the above library and is being regularly updated.

**Comment by amit-isolufy** [comment]
Thanks. @varyamereon appreciate your quick response.

**Comment by albilaga** [comment]
sorry for the late reply. maybe you can try this https://github.com/thisisthekap/Tonestro.Maui.RevenueCat.iOS/pull/5  and build it yourself first? Btw as we are mostly using mac so the strip used on mac only

**Comment by amit-isolufy** [comment]
Thanks @albilaga I have implemented @varyamereon suggested plugins, that is working like charm.

**Comment by thisisthekap** [comment]
obsolete as the new frameworks delivered by revenuecat seem not to have bitcode in them
